import { Routes } from '@angular/router';
import { authGuard, marketingPortalGuard, roleGuard } from './core/auth.guard';

const tenantConsoleChildren: Routes = [
  { path: '', loadComponent: () => import('./features/seller/dashboard.component').then((m) => m.SellerDashboardComponent) },
  { path: 'stores', loadComponent: () => import('./features/seller/stores.component').then((m) => m.SellerStoresComponent) },
  { path: 'stores/:id', loadComponent: () => import('./features/seller/store-editor.component').then((m) => m.StoreEditorComponent) },
  { path: 'products', loadComponent: () => import('./features/seller/products.component').then((m) => m.SellerProductsComponent) },
  { path: 'orders', loadComponent: () => import('./features/seller/orders.component').then((m) => m.SellerOrdersComponent) },
  { path: 'inventory', loadComponent: () => import('./features/seller/inventory.component').then((m) => m.SellerInventoryComponent) },
  { path: 'ads', loadComponent: () => import('./features/seller/ads.component').then((m) => m.SellerAdsComponent) },
  { path: 'domains', loadComponent: () => import('./features/seller/domains.component').then((m) => m.SellerDomainsComponent) },
  { path: 'api-keys', loadComponent: () => import('./features/seller/api-keys.component').then((m) => m.SellerApiKeysComponent) },
  { path: 'webhooks', loadComponent: () => import('./features/seller/webhooks.component').then((m) => m.SellerWebhooksComponent) },
  { path: 'ai', loadComponent: () => import('./features/seller/ai.component').then((m) => m.SellerAiComponent) },
  { path: 'analytics', loadComponent: () => import('./features/seller/analytics.component').then((m) => m.SellerAnalyticsComponent) },
  { path: 'departments/finance', loadComponent: () => import('./features/seller/accounting.component').then((m) => m.SellerAccountingComponent), data: { page: 'overview' } },
  { path: 'accounting', redirectTo: 'departments/finance', pathMatch: 'full' },
  { path: 'accounting/invoices', loadComponent: () => import('./features/seller/accounting.component').then((m) => m.SellerAccountingComponent), data: { page: 'invoices' } },
  { path: 'accounting/payments', loadComponent: () => import('./features/seller/accounting.component').then((m) => m.SellerAccountingComponent), data: { page: 'payments' } },
  { path: 'accounting/expenses', loadComponent: () => import('./features/seller/accounting.component').then((m) => m.SellerAccountingComponent), data: { page: 'expenses' } },
  { path: 'accounting/procurement', loadComponent: () => import('./features/seller/accounting.component').then((m) => m.SellerAccountingComponent), data: { page: 'procurement' } },
  { path: 'accounting/vendors', loadComponent: () => import('./features/seller/accounting.component').then((m) => m.SellerAccountingComponent), data: { page: 'vendors' } },
  { path: 'accounting/chart-of-accounts', loadComponent: () => import('./features/seller/accounting.component').then((m) => m.SellerAccountingComponent), data: { page: 'accounts' } },
  { path: 'accounting/journals', loadComponent: () => import('./features/seller/accounting.component').then((m) => m.SellerAccountingComponent), data: { page: 'journals' } },
  { path: 'accounting/reports', loadComponent: () => import('./features/seller/accounting.component').then((m) => m.SellerAccountingComponent), data: { page: 'reports' } },
  { path: 'accounting/reconciliation', loadComponent: () => import('./features/seller/accounting.component').then((m) => m.SellerAccountingComponent), data: { page: 'reconciliation' } },
  { path: 'departments/sales', loadComponent: () => import('./features/seller/sales.component').then((m) => m.SellerSalesComponent), data: { page: 'overview' } },
  { path: 'sales', redirectTo: 'departments/sales', pathMatch: 'full' },
  { path: 'sales/leads', loadComponent: () => import('./features/seller/sales.component').then((m) => m.SellerSalesComponent), data: { page: 'leads' } },
  { path: 'sales/pipeline', loadComponent: () => import('./features/seller/sales.component').then((m) => m.SellerSalesComponent), data: { page: 'pipeline' } },
  { path: 'sales/quotes', loadComponent: () => import('./features/seller/sales.component').then((m) => m.SellerSalesComponent), data: { page: 'quotes' } },
  { path: 'sales/customers', loadComponent: () => import('./features/seller/sales.component').then((m) => m.SellerSalesComponent), data: { page: 'customers' } },
  { path: 'departments/operations', loadComponent: () => import('./features/seller/operations.component').then((m) => m.SellerOperationsComponent), data: { page: 'overview' } },
  { path: 'operations', redirectTo: 'departments/operations', pathMatch: 'full' },
  { path: 'operations/fulfillment', loadComponent: () => import('./features/seller/operations.component').then((m) => m.SellerOperationsComponent), data: { page: 'fulfillment' } },
  { path: 'operations/inventory', loadComponent: () => import('./features/seller/operations.component').then((m) => m.SellerOperationsComponent), data: { page: 'inventory' } },
  { path: 'operations/catalog', loadComponent: () => import('./features/seller/operations.component').then((m) => m.SellerOperationsComponent), data: { page: 'catalog' } },
  { path: 'departments/marketing', loadComponent: () => import('./features/seller/marketing.component').then((m) => m.SellerMarketingComponent), data: { page: 'overview' } },
  { path: 'marketing', redirectTo: 'departments/marketing', pathMatch: 'full' },
  { path: 'marketing/campaigns', loadComponent: () => import('./features/seller/marketing.component').then((m) => m.SellerMarketingComponent), data: { page: 'campaigns' } },
  { path: 'marketing/performance', loadComponent: () => import('./features/seller/marketing.component').then((m) => m.SellerMarketingComponent), data: { page: 'performance' } },
  { path: 'departments/:dept', loadComponent: () => import('./features/seller/department.component').then((m) => m.SellerDepartmentComponent) },
  { path: 'users', loadComponent: () => import('./features/seller/users.component').then((m) => m.SellerUsersComponent) },
  { path: 'settings', loadComponent: () => import('./features/seller/settings.component').then((m) => m.SellerSettingsComponent) },
  { path: 'profile', loadComponent: () => import('./features/seller/profile.component').then((m) => m.SellerProfileComponent) },
  { path: 'account', redirectTo: 'profile', pathMatch: 'full' },
  { path: 'activity', loadComponent: () => import('./features/seller/activity.component').then((m) => m.SellerActivityComponent) },
  { path: 'logs', redirectTo: 'activity', pathMatch: 'full' },
  { path: 'backups', loadComponent: () => import('./features/seller/backups.component').then((m) => m.SellerBackupsComponent) },
  { path: 'support', loadComponent: () => import('./features/seller/support.component').then((m) => m.TenantSupportComponent) },
];

export const routes: Routes = [
  {
    path: 'admin/login',
    loadComponent: () => import('./features/auth/console-login.component').then((m) => m.ConsoleLoginComponent),
    data: { portal: 'admin' },
  },
  {
    path: 'tenant/login',
    loadComponent: () => import('./features/auth/console-login.component').then((m) => m.ConsoleLoginComponent),
    data: { portal: 'tenant' },
  },
  { path: 'seller/login', redirectTo: 'tenant/login' },
  { path: 'tenants/login', redirectTo: 'tenant/login' },
  {
    path: '',
    canActivate: [marketingPortalGuard],
    loadComponent: () => import('./layout/shell.component').then((m) => m.ShellComponent),
    children: [
      { path: '', loadComponent: () => import('./features/marketplace/home.component').then((m) => m.HomeComponent) },
      { path: 'products', loadComponent: () => import('./features/marketplace/catalog.component').then((m) => m.CatalogComponent) },
      { path: 'products/:slug', loadComponent: () => import('./features/marketplace/product.component').then((m) => m.ProductComponent) },
      { path: 'stores', loadComponent: () => import('./features/marketplace/stores.component').then((m) => m.StoresComponent) },
      { path: 'stores/:slug', loadComponent: () => import('./features/marketplace/store.component').then((m) => m.StoreComponent) },
      { path: 'login', loadComponent: () => import('./features/auth/login.component').then((m) => m.LoginComponent) },
      { path: 'register', loadComponent: () => import('./features/auth/register.component').then((m) => m.RegisterComponent) },
      {
        // OAuth redirect target for customer social login.
        path: 'auth/callback/:provider',
        loadComponent: () => import('./features/auth/social-callback.component').then((m) => m.SocialCallbackComponent),
      },
      { path: 'cart', canActivate: [authGuard], loadComponent: () => import('./features/customer/cart.component').then((m) => m.CartComponent) },
      { path: 'checkout', canActivate: [authGuard], loadComponent: () => import('./features/customer/checkout.component').then((m) => m.CheckoutComponent) },
      { path: 'quotes', canActivate: [authGuard], loadComponent: () => import('./features/customer/quotes.component').then((m) => m.CustomerQuotesComponent) },
      { path: 'orders', canActivate: [authGuard], loadComponent: () => import('./features/customer/orders.component').then((m) => m.OrdersComponent) },
      { path: 'orders/:id', canActivate: [authGuard], loadComponent: () => import('./features/customer/order-detail.component').then((m) => m.OrderDetailComponent) },
      { path: 'sell', canActivate: [authGuard], loadComponent: () => import('./features/auth/sell.component').then((m) => m.SellComponent) },
      { path: 'profile', canActivate: [authGuard], loadComponent: () => import('./features/seller/profile.component').then((m) => m.SellerProfileComponent) },
      { path: 'account', redirectTo: 'profile', pathMatch: 'full' },
    ],
  },
  {
    path: 'tenant',
    canActivate: [roleGuard('tenant_owner', 'store_staff')],
    loadComponent: () => import('./layout/seller-shell.component').then((m) => m.SellerShellComponent),
    children: tenantConsoleChildren,
  },
  {
    path: 'tenants',
    canActivate: [roleGuard('tenant_owner', 'store_staff')],
    loadComponent: () => import('./layout/seller-shell.component').then((m) => m.SellerShellComponent),
    children: tenantConsoleChildren,
  },
  {
    path: 'seller',
    canActivate: [roleGuard('tenant_owner', 'store_staff')],
    loadComponent: () => import('./layout/seller-shell.component').then((m) => m.SellerShellComponent),
    children: tenantConsoleChildren,
  },
  {
    path: 'admin',
    canActivate: [roleGuard('super_admin')],
    loadComponent: () => import('./layout/admin-shell.component').then((m) => m.AdminShellComponent),
    children: [
      { path: '', loadComponent: () => import('./features/admin/dashboard.component').then((m) => m.AdminDashboardComponent) },
      { path: 'tenants', loadComponent: () => import('./features/admin/tenants.component').then((m) => m.AdminTenantsComponent) },
      { path: 'users', loadComponent: () => import('./features/admin/users.component').then((m) => m.AdminUsersComponent) },
      { path: 'subscriptions', loadComponent: () => import('./features/admin/subscriptions.component').then((m) => m.AdminSubscriptionsComponent) },
      { path: 'settings', loadComponent: () => import('./features/admin/settings.component').then((m) => m.AdminSettingsComponent) },
      { path: 'security', loadComponent: () => import('./features/admin/security.component').then((m) => m.AdminSecurityComponent) },
      { path: 'orders', loadComponent: () => import('./features/admin/orders.component').then((m) => m.AdminOrdersComponent) },
      { path: 'audit', loadComponent: () => import('./features/admin/audit.component').then((m) => m.AdminAuditComponent) },
      { path: 'logs', redirectTo: 'audit', pathMatch: 'full' },
      { path: 'analytics', loadComponent: () => import('./features/admin/analytics.component').then((m) => m.AdminAnalyticsComponent) },
      { path: 'domains', loadComponent: () => import('./features/admin/domains.component').then((m) => m.AdminDomainsComponent) },
      { path: 'ads', loadComponent: () => import('./features/admin/ads.component').then((m) => m.AdminAdsComponent) },
      {
        path: 'support',
        loadComponent: () => import('./features/admin/support-overview.component').then((m) => m.AdminSupportOverviewComponent),
      },
      {
        path: 'support/tickets',
        loadComponent: () => import('./features/admin/support-tickets.component').then((m) => m.AdminSupportTicketsComponent),
      },
      {
        path: 'support/chats',
        loadComponent: () => import('./features/admin/support-chats.component').then((m) => m.AdminSupportChatsComponent),
      },
      {
        path: 'support/tasks',
        loadComponent: () => import('./features/admin/support-tasks.component').then((m) => m.AdminSupportTasksComponent),
      },
      {
        path: 'support/guides',
        loadComponent: () => import('./features/admin/support-guides.component').then((m) => m.AdminSupportGuidesComponent),
      },
      { path: 'profile', loadComponent: () => import('./features/seller/profile.component').then((m) => m.SellerProfileComponent) },
      { path: 'account', redirectTo: 'profile', pathMatch: 'full' },
    ],
  },
  { path: '**', redirectTo: '' },
];
